apiVersion: v1
kind: Service
metadata:
  name: {{{ .global.Rafay.WorkloadName }}}
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: {{{ .global.Rafay.WorkloadName }}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{ .global.Rafay.WorkloadName }}}
spec:
  selector:
    matchLabels:
      app: {{{ .global.Rafay.WorkloadName }}}
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{{ .global.Rafay.WorkloadName }}}
        version: "1.0"
    spec:
      containers:
      - name: {{{ .global.Rafay.WorkloadName }}}
        image: hashicorp/http-echo
        args:
        - "-text=Prod"
        ports:
        - containerPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{{ .global.Rafay.WorkloadName }}}
  labels:
    app: {{{ .global.Rafay.WorkloadName }}}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{{ .global.Rafay.WorkloadName }}}-{{{ .global.Rafay.ClusterName }}}.{{{ .global.Rafay.ClusterLabels.ingressDomain }}}
      secretName: nvidia-tls
  rules:
    - host: {{{ .global.Rafay.WorkloadName }}}-{{{ .global.Rafay.ClusterName }}}.{{{ .global.Rafay.ClusterLabels.ingressDomain }}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{{ .global.Rafay.WorkloadName }}}
                port:
                  number: 80
